CREATE TABLE `update_db` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `owner_id` int(11) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `last_modified_user` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `update_db` (`name`, `owner_id`, `date_created`, `date_modified`, `last_modified_user`) VALUES 
("updateVersion0.1.10.sql", "1", NOW(), NOW(), "1"), 
("updateVersion0.1.14.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.1.15.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.1.16.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.1.34.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.1.36.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.06.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.10.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.12.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.39.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.41.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.42.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.46.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.50.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.52.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.54.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.56.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.61.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.65.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.69.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.70.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.73.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.2.82.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.06.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.12.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.17.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.20.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.23.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.34.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.41.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.45.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.46.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.47.sql", "1", NOW(), NOW(), "1"),
("updateVersion0.3.64.sql", "1", NOW(), NOW(), "1");