<h2><strong>Privacy Policy</strong></h2>
<p><span style="font-weight: 400;">We keep your name, email and company so you can use our system. We place cookies on your browser to make our system faster. We may use your name and email to send you information about our system. Please keep your personal information up to date. We will not sell your information to outside companies. You may stop receiving information from us at any time. You are responsible for maintaining the privacy of data you enter into our system. We keep your data very private on our in-house servers and cloud providers. We follow the laws of all the countries where we operate. We follow the laws of Europe, like GDPR. If you need more information, see the sections below.</span></p>
<ol>
    <li><strong> Information DolphinNext May Collect From You</strong></li>
    <p><span style="font-weight: 400;">Our primary goals in collecting information are to provide distributed data management, processing and analysis services to you, to improve our Site, features, content, and to run our core.</span></p>
    <li style="font-weight: 400;"><strong>Metadata Information That You Voluntarily Provide</strong>
        <p><span style="font-weight: 400;">DolphinNext collects and stores the metadata of different types of experiments (RNA-Seq, etc), derived from humans or other organisms, that you submit to the site and other information related to such data. You agree to and accept full responsibility for obtaining all necessary permissions and informed consents from the donors of all samples from which your submitted data is derived.</span></p>
    </li>
    <li style="font-weight: 400;"><strong>User Account Information/Personally Identifiable Information</strong>
        <p><span style="font-weight: 400;">When you register with us through the Site and during your use of the Site, we will ask you for personally-identifiable information, which is information about you that can be used to contact or identify you ("Personal Information"), such as: your name, company or organization name, title, e-mail address, postal address, telephone numbers, and, if you sign up for a paid account, and billing information. If you contact us, we may also keep a record of that correspondence or communication, including any Personal Information it contains.</span></p>
    </li>
    <li style="font-weight: 400;"><strong>Cookies and Tracking Pixels</strong>
        <p><span style="font-weight: 400;">We use cookies, tracking pixels, and other similar technologies to track activity on our Site and to enhance the functionality of our Site. Cookies are small data files that our web servers send to your browser and which get saved on the hard drive of the computer that you are using to access the Site. If you do not want to allow cookies on your computer, most browsers have a feature that allows you either to automatically decline cookies or to decline or accept particular cookies from particular web sites. If you choose to reject cookies from our Site, you may be unable to use certain Site services, features, and functionality. If you choose to accept cookies from us and our service providers, you are agreeing to let us and our service providers install cookies on your computer. To learn more about cookies, please visit </span><a href="http://allaboutcookies.org/"><span style="font-weight: 400;">http://allaboutcookies.org</span></a><span style="font-weight: 400;">. Tracking pixels (also known as web beacons, action tags, or transparent GIF files) collect and store information about your visits to our Site, such as page visits, the duration of the visit, the specific link(s) that you clicked during your visit, and the address of the website from which you arrived at the Site.</span></p>
    </li>
    <li style="font-weight: 400;"><strong>User Software and Reference Data</strong>
        <p><span style="font-weight: 400;">You may also be permitted to upload your own software and data, including reference genomes, to the Site in the course of using the Site. You agree to and accept full responsibility for obtaining all permissions, consents, and rights necessary for uploading and using any such software and data to and with the Site. The software you upload must comply with the DolphinNext&rsquo;s &ldquo;Terms of Use Policy&rdquo;.</span></p>
    </li>
    <li><strong> Security of Your Information</strong>
        <p><span style="font-weight: 400;">Our Site uses Secure Socket Layer (SSL) encryption to protect sequence data that users upload to the Site over the Internet. However, no data transmission over the Internet or data storage system can be 100% secure. As a result, while we strive to protect your information, we cannot guarantee the security of information you transmit to us, we transmit to you, or that we store on your behalf. If at any time you believe that your interaction with the Site or information is no longer secure, please inform us immediately.</span></p>
        <p><span style="font-weight: 400;">Further, if you register and create a profile on the Site, your profile, Personal Information, and sequence data submitted by you to the Site will be password- protected. You agree that you will be responsible for all actions taken under an authenticated login. Accordingly, we recommend that you select a strong password and do not divulge that password to anyone. Also, be certain to sign out of your DolphinNext account and close your browser window when you have finished using the Site to prevent others from accessing your information and data.</span></p>
        <p><span style="font-weight: 400;">Please note that while the Site includes a service for storing your sequence data, which is backed up, we cannot guarantee that such sequence data will be secure, reliable, or available. Accordingly, UMMS Biocore will not be responsible for any loss or corruption of data, or any other harm that results from your access to or use of the Site despite the security features of our service described in this policy and elsewhere on DolphinNext.</span></p>
    </li>
    <li><strong> How Your Information May be Used</strong>
        <p><span style="font-weight: 400;">We may use your Personal Information to improve our products and services, to ensure contact information is up to date and accurate, to improve our customer service, to reduce risk and prevent fraud, to provide you with a personalized experience on our Site and to communicate with you regarding new service features and related products and services provided by our partners, events, and other information and notices we believe you may find interesting or useful. We will not sell or provide your information to third parties for their own direct marketing purposes.</span></p>
        <p><span style="font-weight: 400;">We use the automatic usage and other non-Personal Information collected to maintain, secure, and improve our Site, and to understand your interests when visiting our Site. We may generate statistical information regarding our user-base and use it to analyze our Site or business.</span></p>
    </li>
    <li><strong> Changing or Deleting Your Information</strong>
        <p><span style="font-weight: 400;">You may review, update, correct or delete the Personal Information you provide to us by contacting us. If you completely delete all such information, then your account may become deactivated. If you would like us to delete your account in our system, please contact us at </span><span style="font-weight: 400;">support@dolphinnext.com</span><span style="font-weight: 400;"> with a request that we delete your Personal Information from our database. We will use commercially reasonable efforts to honor your request. We may retain an archived copy of your records as required by law or for legitimate business purposes.</span></p>
    </li>
    <li><strong> Limiting Use in Our Email List</strong>
        <p><span style="font-weight: 400;">If you no longer wish to receive new product/service notices, email newsletters or other future promotional communications from us, please follow the opt- out instructions included in each such communication or notify us by email at </span><span style="font-weight: 400;">support@dolphinnext.com</span><span style="font-weight: 400;"> with the word "remove" in the subject header, and we will remove your name from our email recipient list. You may not, however, opt out of necessary service or account maintenance notices or other administrative and transactional notices.</span></p>
    </li>
    <li><strong> Users Under 13 Years of Age</strong>
        <p><span style="font-weight: 400;">This Site and our services are not directed towards users under the age of 13 and we do not knowingly collect Personal Information from users under the age of 13. If a parent or guardian becomes aware that his or her child under the age of 13 has provided us with Personal Information without their consent, he or she should contact us at </span><span style="font-weight: 400;">support@dolphinnext.com</span><span style="font-weight: 400;">. If we become aware that a child under 13 has provided us with Personal Information, we will delete such information from our files.</span></p>
    </li>
    <li><strong> Links and Third Party Applications</strong>
        <p><span style="font-weight: 400;">On the Site, we may provide links to websites or applications maintained by third parties, which we believe you may find useful. UMMS Biocore is not responsible for the privacy practices of these other websites or applications and we encourage you to review the privacy policies of each of those other websites or applications before using such websites and applications. If you click on these third-party links, these other websites or applications may place their own cookies or other files on your computer, collect data, or solicit Personal Information from you. Other websites and applications will have different policies and rules regarding the use or disclosure of the personal information you submit to them. We make no representation with regard to the policies or business practices of any websites or applications to which you connect through a link from this Site, and are not responsible for any material contained on, or any transactions that occur between you and any such website or application.</span></p>
    </li>
    <li><strong> Location</strong>
        <p><span style="font-weight: 400;">UMMS Biocore is a United States based entity and therefore we must abide by the laws and regulations of the United States as well as the other countries where we operate. By providing Personal Information and other information to this Site, you understand and consent to the collection, use, processing and transfer of such information to the United States and other countries or territories, which may not offer the same level of data protection as the country where you reside, in accordance with the terms of this Privacy Policy.</span></p>
    </li>
    <li><strong> Privacy Policy Changes</strong>
        <p><span style="font-weight: 400;">This Privacy Policy may be updated periodically. We will notify you of any material changes to this Privacy Policy by posting the revised policy on the Site. You are advised to periodically review this page to ensure continuing familiarity with the most current version of our Privacy Policy. Any changes to our Privacy Policy will become effective upon our posting of the revised Privacy Policy on the Site. Use of the Site following such changes constitutes your acceptance of the revised Privacy Policy then in effect. You will be able to determine when this Privacy Policy was last revised by checking the "Last Updated" information that appears at the top of this page.</span></p>
    </li>
    <li><strong> Questions or Concerns</strong>
        <p><span style="font-weight: 400;">If you have any questions, comments, or concerns regarding this Policy, please contact us by email at </span><span style="font-weight: 400;">support@dolphinnext.com.</span></p>
    </li>
</ol>
