<h1><strong>TERMS AND CONDITIONS</strong></h1>
<h2><strong>1. ACCEPTANCE OF THE TERMS OF USE</strong></h2>
<p><span style="font-weight: 400;">The following terms and conditions, together with any referenced documents (collectively, &ldquo;</span><strong>Terms of Use</strong><span style="font-weight: 400;">&ldquo;) form a legal agreement between you and your employer, employees, agents, contractors and any other entity on whose behalf you accept these terms (collectively, &ldquo;</span><strong>you</strong><span style="font-weight: 400;">&rdquo; and &ldquo;</span><strong>your</strong><span style="font-weight: 400;">&rdquo;), and UMMS Bioinformatics Core (&ldquo;</span><strong>UMMS</strong> <strong>Biocore</strong><span style="font-weight: 400;">,&rdquo; &ldquo;</span><strong>we</strong><span style="font-weight: 400;">,&rdquo; &ldquo;</span><strong>us</strong><span style="font-weight: 400;">&rdquo; and &ldquo;</span><strong>our</strong><span style="font-weight: 400;">&rdquo;). The Terms of Use apply to the demonstration services available on DolphinNext where these Terms of Use are presented.</span></p>
<p><span style="font-weight: 400;">By accessing or using </span><strong>DolphinNext</strong><span style="font-weight: 400;">, or by clicking to accept or agree to the Terms of Use when this option is made available to you, you represent that you have read and understood, and agree to be bound by these Terms of Use. If you do not agree to these Terms of Use, you may not use </span><strong>DolphinNext</strong><span style="font-weight: 400;">.</span></p>
<p><span style="font-weight: 400;">Personally identifiable information collected about you by </span><strong>DolphinNext</strong><span style="font-weight: 400;"> is treated in accordance with the Privacy Policy, which is hereby incorporated into these Terms of Use by reference. If you do not agree to these Terms of Use or the Privacy Policy, you must accept these Terms of Use or access DolphinNext.</span></p>
<p><span style="font-weight: 400;">We reserve the right to terminate or modify DolphinNext in whole or in part, in any manner in our sole discretion, without notice.</span></p>
<p><span style="font-weight: 400;">To access portions of DolphinNext or certain resources, you may be asked to provide certain registration details or other information.&nbsp; It is a condition of your use of </span><strong>&nbsp;DolphinNext</strong><span style="font-weight: 400;">, and you hereby represent and warrant that all information you provide is correct, current and complete. You agree that you are solely responsible to us for all activities identified with your access and registration. </span><strong>UMMS Biocore</strong><span style="font-weight: 400;"> has the absolute right to disable any user name or password, at any time, for any reason, including if in our sole discretion, we believe that you have failed to comply with any provision of these Terms of Use.</span></p>
<h2><strong>2. PROHIBITED USES</strong></h2>
<p><span style="font-weight: 400;">You agree not to access or use (and shall not permit others to access or use) DolphinNext in any manner:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">To process, use, transmit or introduce any confidential or sensitive information of any kind, including personally identifiable information, sensitive personal data, health information of any kind, or factual data regarding your employees or third data, and particularly excluding: (1) information protected under the privacy or security regulations issued pursuant to the Health Insurance Portability and Accountability Act of 1996 (HIPAA) or subject to the Health Information Technology for Economic and Clinical Health (HITECH) Act; or (2) non‑public sensitive or personally identifiable information including but not limited to drivers license numbers, passport numbers, social security numbers, tax identification numbers, voter registration numbers or similar identifying numbers, health information, or financial information including bank, checking, credit card, debit card, or other account numbers.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To disassemble, reverse engineer, decompile or modify them or otherwise create derivative works of them.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To access them for the purpose of developing a product or service that competes with DolphinNext.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To use them to create, use, send, store or run viruses or other harmful computer code, files, scripts, agents or other programs or engage in any other malicious act.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To disrupt their security, integrity or operation.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To remove or modify a copyright or other proprietary rights notice in them.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To use them to reproduce, distribute, display, transmit or use material protected by copyright or other intellectual property right (including the rights of publicity or privacy) without first obtaining the permission of the owner.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To use them to damage the property of another.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">That violates any applicable federal, state, local or international law or regulation, or advocates, promotes or assists in any unlawful act, constitutes an illegal threat or violates export control laws.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">That temporarily or permanently alters, erases, removes, copies, modifies, halts or disables any </span><strong>UMMS Biocore</strong><span style="font-weight: 400;"> or third party data, software or network.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">That violates the rights of any person or entity that may give rise to civil or criminal liability under applicable laws or regulations applicable to you, another user, and/or </span><strong>UMMS Biocore</strong><span style="font-weight: 400;">, including violation of privacy or publicity rights, infringement of any copyright, patent, trademark, trade secret or other intellectual property right, or conflicts with these Terms of Use or the Privacy Policy.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To transmit or introduce offensive materials, including those involving profanity, violence, sexual conduct, pornography or discrimination based on race, sex, religion, nationality, disability, sexual orientation or age.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To monitor or attempt to gain unauthorized access to: (1) an account or computer not belonging to you; (2) any data, information or communications on any network or system not owned by you, without authorization; (3) any system or network user accounts or passwords of other users, without authorization; or (4) e‑mail addresses, screen names or other identifiers without the consent of the person identified (including, without limitation, phishing, password robbery, spidering and harvesting).</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">That is false, deceptive, misleading or fraudulent, including but not limited to: (1) any attempt to impersonate any person or entity, including any other user, </span><strong>UMMS Biocore</strong><span style="font-weight: 400;"> or a </span><strong>UMMS Biocore</strong><span style="font-weight: 400;"> employee; (2) to misrepresent your identity or affiliation with any person or organization; and (3) any attempt to give the impression that you are posting materials from any person or entity other than yourself if that is not the case, including but not limited to altering your IP source address.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">To monitor or copy materials on </span><strong>DolphinNext</strong><span style="font-weight: 400;"> for any unauthorized purpose or access </span><strong>DolphinNext</strong><span style="font-weight: 400;"> via any automatic device, process or means of access such as a robot or spider.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">That may have a detrimental effect on </span><strong>DolphinNext&rsquo;s</strong><span style="font-weight: 400;"> function, user interaction or security, including but not limited to: (1) gaining unauthorized access to, or attempting to compromise the security of, any network, system, computing facility, equipment, data or information; (2) attempting to intercept, redirect or otherwise interfere with communications intended for others; (3) disabling, damaging overburdening or impairing </span><strong>DolphinNext</strong><span style="font-weight: 400;"> or any server, computer or database connected to or accessed by </span><strong>DolphinNext</strong><span style="font-weight: 400;">; (4) modifying, blocking or otherwise interfering with the display of </span><strong>DolphinNext</strong><span style="font-weight: 400;">; (5) interfering with another user&rsquo;s ability to access, use and enjoy </span><strong>DolphinNext</strong><span style="font-weight: 400;">; (6) accessing another user&rsquo;s registration information or user account without that user&rsquo;s express written permission; (7) transmitting or introducing any malicious or technologically harmful element to </span><strong>DolphinNext </strong><span style="font-weight: 400;">such as a spyware program, virus, Trojan horse, worm or logic bomb; (8) performing, without </span><strong>UMMS Biocore&rsquo;s</strong><span style="font-weight: 400;"> express prior written authorization, scalability testing, load testing, probing, scanning, penetration or vulnerability testing of </span><strong>DolphinNext</strong><span style="font-weight: 400;">, including without limitation the Community Services; and (9) engaging in any activities that results in any server being the target of a denial of service attack.&nbsp;</span></li>
</ul>
<h2><strong>3. DISCLAIMER OF WARRANTIES</strong></h2>
<p><strong>UMMS Biocore</strong><span style="font-weight: 400;"> cannot and does not promise or warrant that any aspect of </span><strong>DolphinNext</strong><span style="font-weight: 400;"> is free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti‑virus protection and accuracy of data input and output, and for maintaining a means external to our site for the reconstruction of any lost data.&nbsp; WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL‑OF‑SERVICE ATTACK, VIRUSES OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF DOLPHINNEXT OR ANY SERVICES OR ITEMS OBTAINED THROUGH DOLPHINNEXT OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE LINKED TO IT.</span></p>
<p>&nbsp;</p>
<h2><strong>4. COPYRIGHT AND TRADEMARKS</strong></h2>
<p><span style="font-weight: 400;">DolphinNext and relative logos are trademarks or registered trademarks of DolphinNext in US and/or other countries. Other trademarks are proprietary of their respective owners. Other names and brands may be claimed as the property of others.</span></p>
</p>
