#!/bin/sh
db=$1
user_id=${2-1} #default user_id: 1
user=${3-root}
p=${4}
[[ ! -z $p ]] && pass="-p${p}" || pass=""
exist_table=$(mysql -u${user} ${pass} $db -N -s -e  "select count(*) from information_schema.tables where table_schema='${db}' and table_name='update_db';")
echo "INFO: check update_db table:$exist_table"
exist_db=$(mysql -u${user} ${pass} $db -sse "SELECT DISTINCT name FROM update_db;")
#echo "INFO: check applied patches:\n$exist_db"
exist_patch=$(ls -1 patch/)
#echo "INFO: get all patch list:\n$exist_db"
not_exist_db=$(printf "${exist_db}\n${exist_patch}"  | sort | uniq -u | sort -V) 
printf "INFO: Checking db patches that are not applied:\n$not_exist_db\n"

for i in $not_exist_db; do
    success="f"
    if [ -f patch/${i} ]; then
        echo "INFO: Database patch ${i} will be executed."
        mysql -u${user} ${pass} $db < patch/${i} && success="t" && echo "INFO: Database patch ${i} successfully executed."
    fi
    ## if update_db table exist then add as new line
    if [ "$exist_table" -eq 1 ] && [ $success == "t" ]; then
        echo "INFO: update_db will be updated for ${i}."
        mysql -u${user} ${pass} $db -sse "INSERT INTO update_db (name, owner_id, date_created, date_modified, last_modified_user) VALUES (\"${i}\", \"${user_id}\", NOW(), NOW(), \"${user_id}\");" && echo "INFO: update_db table successfully updated" 
    fi
done
echo "INFO: runUpdate Completed."






